apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-config
data:
  hive-site.xml: |
    <configuration>
      <property>
          <name>fs.s3a.connection.ssl.enabled</name>
          <value>false</value>
      </property>
      <property>
          <name>fs.s3a.path.style.access</name>
          <value>true</value>
        </property>

      <property>
        <name>hive.server2.enable.doAs</name>
        <value>false</value>
      </property>
      <property>
        <name>hive.server2.use.SSL</name>
        <value>false</value>
      </property>
      <property>
        <name>hive.server2.authentication</name>
        <value>NOSASL</value>
      </property>
      <property>
        <name>hive.metastore.metrics.enabled</name>
        <value>true</value>
      </property>
      <property>
        <name>hive.server2.metrics.enabled</name>
        <value>true</value>
      </property>
      <property>
        <name>hive.service.metrics.reporter</name>
        <value>JMX</value>
      </property>
      <property>
        <name>hive.server2.thrift.bind.host</name>
        <value>0.0.0.0</value>
      </property>
      <property>
        <name>hive.metastore.thrift.bind.host</name>
        <value>0.0.0.0</value>
      </property>
      <property>
        <name>hive.metastore.uris</name>
        <value>thrift://hive-metastore-0:9083,thrift://hive-metastore-1:9083,thrift://hive-metastore-2:9083</value>
      </property>
      <property>
        <name>datanucleus.schema.autoCreateAll</name>
        <value>false</value>
      </property>
      <property>
        <name>hive.metastore.schema.verification</name>
        <value>false</value>
      </property>
      <property>
        <name>hive.default.fileformat</name>
        <value>Parquet</value>
      </property>
      <property>
        <name>hive.metastore.warehouse.dir</name>
        <value>/opt/hive/warehouse</value>
      </property>
      <property>
        <name>fs.s3a.endpoint</name>
        <value>XXX_S3ENDPOINT_URL_PREFIX_XXXXXX_S3LOCATION_XXX/</value>
      </property>
      <property>
        <name>hive.metastore.db.type</name>
        <value>POSTGRES</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionUserName</name>
        <value>XXX_DATABASE_USER_XXX</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionPassword</name>
        <value>XXX_DATABASE_PASSWORD_XXX</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionURL</name>
        <value>jdbc:XXX_DATABASE_CONNECT_URL_XXX</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionDriverName</name>
        <value>org.postgresql.Driver</value>
      </property>
      <property>
        <name>hive.cluster.delegation.token.store.class</name>
        <value>org.apache.hadoop.hive.thrift.DBTokenStore</value>
      </property>
    </configuration>
