apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
resources:
  - trino-catalog-lodestar-sealedsecret.yaml

patchesStrategicMerge:
  - hive-metastore-dc.yaml
  - hive-config.yaml
  - trino-worker-dc.yaml
  - trino-coordinator-dc.yaml
