apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-coordinator

spec:
  template:
    spec:
      volumes:
        - name: trino-catalogs-volume
          secret:
            secretName: trino-catalog
            defaultMode: 420
            items:
              - key: elasticsearch.properties
                path: elasticsearch.properties
        - $patch: delete
          name: trino-kafka-volume

      containers:
        - name: trino-coordinator
          volumeMounts:
            - $patch: delete
              name: trino-kafka-volume
