apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base

patchesStrategicMerge:
  - jupyterhub-singleuser-profiles-sizes-configmap.yaml
  - jupyterhub-configmap.yaml
  - jupyterhub-db-dc.yaml

commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: jupyterhub