apiVersion: airflow.apache.org/v1alpha1
kind: AirflowCluster
metadata:
  name: pc-cluster
  finalizers:
    - sigapps.k8s.io/cleanup
spec:
  config: {}
  airflowbase:
    name: pc-base
  dags:
    git:
      branch: main
      once: false
      repo: 'https://github.com/masoodfaisal/dags/'
  #    subdir: "dags/"
  executor: Celery
  ui:
    enableroutes: true
    image: quay.io/ml-aml-workshop/airflow-custom
    replicas: 1
    resources: {}
    version: 1.2.0
  scheduler:
    database: hb1g05xelszeg799
    dbuser: yzo16chrm3n05srf
    image: quay.io/ml-aml-workshop/airflow-custom
    resources: {}
    version: 1.2.0
  redis:
    image: redis
    resources: {}
    version: '4.0'
  flower:
    enableroutes: true
    image: quay.io/ml-aml-workshop/airflow-custom
    replicas: 1
    resources: {}
    version: 1.2.0
  worker:
    forceroot: 'false'
    image: quay.io/ml-aml-workshop/airflow-custom
    replicas: 2
    resources: {}
    version: 1.2.0

