apiVersion: airflow.apache.org/v1alpha1
kind: AirflowBase
metadata:
  name: pc-base
  finalizers:
    - sigapps.k8s.io/cleanup
spec:
  postgres:
    image: registry.access.redhat.com/rhscl/postgresql-10-rhel7
    replicas: 1
    resources: {}
    version: latest
  storage:
    image: k8s.gcr.io/volume-nfs
    resources: {}
    version: '0.8'
