apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-coordinator

spec:
  template:
    spec:
      volumes:
        - name: trino-catalogs-volume
          secret:
            secretName: trino-catalog
            defaultMode: 420
            items:
              - key: hive.properties
                path: hive.properties
              - key: customerchurn.properties
                path: customerchurn.properties
              - key: elasticsearch.properties
                path: elasticsearch.properties

        - name: trino-kafka-volume
          secret:
            secretName: trino-catalog
            defaultMode: 420
            items:
              - key: customerchurn.json
                path: customerchurn.json

      containers:
        - name: trino-coordinator
          volumeMounts:
            - name: trino-kafka-volume
              mountPath: /etc/trino/kafka

