# this is not recommended for production or shared environments.
# there are valid rbac roles available and it is recommended to use the right and restrictive roles.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-user-admin-namespace-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: airflow2-core
    namespace: ml-workshop
  - kind: ServiceAccount
    name: default
    namespace: ml-workshop