---
# Source: airflow/charts/redis/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: app-aflow-redis
  namespace: "ml-workshop"
  labels:
    app.kubernetes.io/name: redis
    helm.sh/chart: redis-14.8.11
    app.kubernetes.io/instance: app-aflow
    app.kubernetes.io/managed-by: Helm

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: airflow2
  name: airflow2-core